### ISSUE TITLE
Intermittent build error `The module Reshowcase.Configs is an alias for module Configs-Reshowcase, which is missing`

### ISSUE THREAD

**Issue by maxkorp** [bloodyowl/reshowcase#5]
We get this error like 1/3 of the time when building our project in CI. 

```
/builds/qwick/qwick/node_modules/reshowcase/src/ReshowcaseUi.rei 7:19-45
   
   5 ┆ ~demos: Belt.Map.String.t(
   6 ┆           Belt.Map.String.t(
   7 ┆             Reshowcase.Configs.demoUnit => React.element,
   8 ┆           ),
   9 ┆         )
   
   The module Reshowcase.Configs is an alias for module Configs-Reshowcase, which is missing
```

We previously were using a fork of 1.4.0 with upgraded deps, which worked fine, but since bumping to 2.0.0, we get this fairly often. 

Running in a container based on  `node:12.13-stretch`, bs-platform of `7.2.2` (but previously `7.0.0` was broken as well.

Trying to track this down, but not having any luck. For better or worse, this never happens locally (on macos catalina).

**Comment by bloodyowl** [comment]
Yeah, I also have this bug on CircleCI, but much less often. I've not been to track down the bug source. Is this the CI you're using?

@bobzhang would you have any idea why this compilation error might happen on certain CIs?

**Comment by johnhaley81** [comment]
@bloodyowl I made [this](https://github.com/johnhaley81/reshowcase/commit/ac410ac21852316505bee36de7d3a68aab0857e1) change yesterday which seems to have fixed it for us.

My thought is that using the `namespace` of the project in the interface file of an externally used package introduces some sort of race condition on linux systems. I don't know this for sure but so far we've not had any failing CI tests since then.

**Comment by bloodyowl** [comment]
Oh right @johnhaley81, we often have that bug on CIs with our application code, and I've never been able to track down where it came from, I didn't notice the module in the interface file. Thanks!

reshowcase@2.0.1 has been published on npm with the fix.

**Comment by maxkorp** [comment]
Thanks dude!
